//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentRepairEngine.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLog
    {
        public int ActionLogID { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public int UserID { get; set; }
        public int ActionStatusID { get; set; }
        public string Descryption { get; set; }
    
        public virtual ActionStatus ActionStatus { get; set; }
        public virtual User User { get; set; }
    }
}
