//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentRepairEngine.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OdbRepairEngineEntities : DbContext
    {
        public OdbRepairEngineEntities()
            : base("name=OdbRepairEngineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionLog> ActionLog { get; set; }
        public virtual DbSet<ActionStatus> ActionStatus { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<HomeTech> HomeTech { get; set; }
        public virtual DbSet<ModelTechFactory> ModelTechFactory { get; set; }
        public virtual DbSet<NewMessage> NewMessage { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<RequestStatus> RequestStatus { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TechColor> TechColor { get; set; }
        public virtual DbSet<TechFactory> TechFactory { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
