//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentRepairEngine.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Comment = new HashSet<Comment>();
            this.NewMessage = new HashSet<NewMessage>();
        }
    
        public int RequestID { get; set; }
        public System.DateTime StartDate { get; set; }
        public int HomeTechID { get; set; }
        public int TechFactory { get; set; }
        public int ModelTechFactoryID { get; set; }
        public int TechColorID { get; set; }
        public string ProblemeDescryption { get; set; }
        public int RequestStatusID { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string RepairParts { get; set; }
        public Nullable<int> MasterID { get; set; }
        public int ClientID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual HomeTech HomeTech { get; set; }
        public virtual ModelTechFactory ModelTechFactory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewMessage> NewMessage { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual TechColor TechColor { get; set; }
        public virtual TechFactory TechFactory1 { get; set; }
    }
}
